language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - py.cleanup -p && py.test --platform=MAC --browser=safari --environment=staging --alluredir ExecutionReports/